source-item-ordering = ['enum', 'impl', 'module', 'struct', 'trait']

module-item-order-groupings = [
  ["use",              ["use"]],
  ["macros",           ["macro"]],
  ["modules",          ["extern_crate", "mod", "foreign_mod"]],
  ["global_asm",       ["global_asm"]],
  ["UPPER_SNAKE_CASE", ["static", "const"]],
  ["PascalCase",       ["ty_alias", "enum", "struct", "union", "trait", "trait_alias", "impl"]],
  ["lower_snake_case", ["fn"]],
]

module-items-ordered-within-groupings = [
  "use",
  "macros",
  "modules",
  "global_asm",
  "UPPER_SNAKE_CASE",
  "lower_snake_case",
]
